### ISSUE TITLE
Reshaping s array with / division operator results in float which raises an error

### ISSUE THREAD

**Issue by cidetraq** [tompollard/sammon#6]
In here: 
`# Use step-halving procedure to ensure progress is made`
        
    for j in range(maxhalves):
            s_reshape = s.reshape(2,len(s)/2).T`

When I tried to use your function with a matrix of shape (2400, 20) and setting init='random' I got the error 

> 'float' object cannot be interpreted as an integer

To fix this I changed the code to 
`s_reshape = s.reshape(2,len(s)//2).T`

I was getting a different error when I left the default setting of init='pca', something like 2 (dim 1) != 1 (dim 0) and I couldn't figure that one out so I went with init='random'.

**Comment by tompollard** [comment]
Thanks @cidetraq, it's been a while since I looked at this repo, but I'll try to get this bug fixed.

**Comment by devernay** [comment]
Actually, this code is still wrong for n != 2.
This is fixed in https://github.com/tompollard/sammon/pull/8

**Comment by tompollard** [comment]
Fixed (thanks @devernay!)
